# Generated by Django 4.0.2 on 2022-03-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thinkers', '0010_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
